### ISSUE TITLE
[BUG] QEMIST Cloud credentials improperly checked when submitting jobs to IonQ Cloud

### ISSUE THREAD

**Issue by MPCoons** [goodchemistryco/Tangelo#206] opened 2022-09-08 20:02 UTC
# Issue: Bug Report

**Expected Behavior**
Running the attached Python script via "python minimum_example.py" is expected to

1. Create a SecondQuantizedMolecule for ground state H2 / STO-3G basis set.
2. Perform classical VQE to obtain the optimal QCC circuit for this system.
3. Connect with IonQ Cloud's API and submit the job to the simulator backend.
4. Return a histogram from the simulation.

**Current Behavior**
The job fails before connecting to IonQ Cloud and never submits the simulation to the simulator backend. Several errors related to the remote end disconnecting without response, a protocol error, and a connection error are reported. The full error message is attached to this report along with an example.

**Steps to Reproduce (minimal example)**
The job fails at Step 3 below.

1. Set the environment variable IONQ_APIKEY to its current value.
2. Activate the appropriate environment with the installation of tangelo-gc  v0.3.2.
3. Run the script with "python  minimum_example.py"

**Environment**
CentOS Linux release 7.8.2003 (Core)
The output of `conda list` is attached to this report. Briefly, tangelo-gc v0.3.2 and qemist-client v0.5.0 are installed.

**Possible Solution**
Commenting the line `from .qemist_cloud_connection import job_submit, job_status, job_cancel, job_result, job_estimate`  in `tangelo/linq/qpu_connection/__init__.py` fixed the issue.

[tangelo-gc_conda_env.txt](https://github.com/goodchemistryco/Tangelo/files/9530255/tangelo-gc_conda_env.txt)
[minimum_example_error.txt](https://github.com/goodchemistryco/Tangelo/files/9530256/minimum_example_error.txt)
[minimum_example_py.txt](https://github.com/goodchemistryco/Tangelo/files/9530257/minimum_example_py.txt)

**Comment by ValentinS4t1qbit** [comment] 2022-09-08 21:34
We indeed should not check or import anything QEMIST Cloud related unless the user explicitly use a feature that requires it.

A good way to make that clean is probably by encapsulating the qemist cloud "job" functions in `qemist_cloud_connection.py` in a `QCloudConnection` children class of `QPUConnection`, and hide the import / login checks inside the call to `__init__` (e.g unless the class is instantiated, users won't have any issue of imports. If the imports work at instantiation, there is no reason to check them for the other job methods).

The qemist cloud notebook should then be modified to reflect these changes, and we should make sure to tell our developer friends at QEMIST Cloud that they should include a link to that notebook in their documentation, so that its always up to date.

On top of making things cleaner, the class encapsulation paves the way for handling multi-cloud services through QEMIST Cloud in a more resilient manner.

Any comments ?

**Comment by MPCoons** [comment] 2022-09-09 14:16
I agree. Consistency between all current and future CloudConnection children classes of QPUConnection is probably the cleanest and most logical approach. Also, it doesn't seem like doing this for the qemist cloud routines would require substantial effort.

**Comment by AlexandreF-1qbit** [comment] 2022-09-09 14:30
I confirm that I am able to reproduce the bug. It is indeed due to the `from .qemist_cloud_connection import job_submit, job_status, job_cancel, job_result, job_estimate` line. Will come back soon with a fix.

**Comment by ValentinS4t1qbit** [comment] 2022-09-12 16:18
Fixed with #207

**Closed by ValentinS4t1qbit** 2022-09-12 16:18 UTC
Labels: bug
